/*----- PROTECTED REGION ID(HdbEventSubscriberStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: HdbEventSubscriberStateMachine.cpp,v 1.3 2014-03-07 14:05:54 graziano Exp $";
//=============================================================================
//
// file :        HdbEventSubscriberStateMachine.cpp
//
// description : C++ source for the HdbEventSubscriber and its alowed
//               methods for commands and attributes
//
// project :     Tango Device Server.
//
// $Author: graziano $
//
// $Revision: 1.3 $
// $Date: 2014-03-07 14:05:54 $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source: /home/cvsadm/cvsroot/fermi/servers/hdb++/hdb++es/src/HdbEventSubscriberStateMachine.cpp,v $
// $Log: HdbEventSubscriberStateMachine.cpp,v $
// Revision 1.3  2014-03-07 14:05:54  graziano
// added ResetStatistics command
//
// Revision 1.2  2014-02-20 15:13:05  graziano
// name and path fixing
// regenerated with new pogo
//
// Revision 1.1  2013-07-17 13:37:43  graziano
// *** empty log message ***
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <HdbEventSubscriber.h>
#include <HdbEventSubscriberClass.h>

/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::HdbEventSubscriberStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  Archiving running and everything is OK.
//  ALARM   |  One or more attributes faulty or FIFO size above threshold
//  OFF     |  Archiving stopped
//  FAULT   |  All attributes faulty


namespace HdbEventSubscriber_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeOkNumber_allowed()
 *	Description : Execution allowed for AttributeOkNumber attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeOkNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributeOkNumber attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeOkNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeOkNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeNokNumber_allowed()
 *	Description : Execution allowed for AttributeNokNumber attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeNokNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributeNokNumber attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeNokNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeNokNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributePendingNumber_allowed()
 *	Description : Execution allowed for AttributePendingNumber attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributePendingNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributePendingNumber attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributePendingNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributePendingNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeNumber_allowed()
 *	Description : Execution allowed for AttributeNumber attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributeNumber attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeList_allowed()
 *	Description : Execution allowed for AttributeList attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeList_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributeList attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeListStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeListStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeOkList_allowed()
 *	Description : Execution allowed for AttributeOkList attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeOkList_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributeOkList attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeOkListStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeOkListStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeNokList_allowed()
 *	Description : Execution allowed for AttributeNokList attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeNokList_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributeNokList attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeNokListStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeNokListStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributePendingList_allowed()
 *	Description : Execution allowed for AttributePendingList attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributePendingList_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributePendingList attribute in read access.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributePendingListStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributePendingListStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeAdd_allowed()
 *	Description : Execution allowed for AttributeAdd attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeAdd_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AttributeAdd command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeAddStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeAddStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeRemove_allowed()
 *	Description : Execution allowed for AttributeRemove attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeRemove_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AttributeRemove command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeRemoveStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeRemoveStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeStatus_allowed()
 *	Description : Execution allowed for AttributeStatus attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeStatus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AttributeStatus command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeStatusStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeStatusStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::StartStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::StopStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::StopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeStart_allowed()
 *	Description : Execution allowed for AttributeStart attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeStart_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AttributeStart command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeStartStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeStartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_AttributeStop_allowed()
 *	Description : Execution allowed for AttributeStop attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_AttributeStop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AttributeStop command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::AttributeStopStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::AttributeStopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : HdbEventSubscriber::is_ResetStatistics_allowed()
 *	Description : Execution allowed for ResetStatistics attribute
 */
//--------------------------------------------------------
bool HdbEventSubscriber::is_ResetStatistics_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ResetStatistics command.
	/*----- PROTECTED REGION ID(HdbEventSubscriber::ResetStatisticsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	HdbEventSubscriber::ResetStatisticsStateAllowed
	return true;
}

}	//	End of namespace
